-- Auto-generated from schema-map-postgres.psd1 (map@62c9c93)
-- engine: postgres
-- table:  retention_enforcement_jobs
CREATE TABLE IF NOT EXISTS retention_enforcement_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_id BIGINT NOT NULL,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  processed_count BIGINT NOT NULL DEFAULT 0,
  error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_rej_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);
